# Generated by Django 4.2.7 on 2025-07-23 17:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('SELLER', 'Satıcının hüquq və öhdəlikləri'), ('BUYER', 'Alıcının hüquq və öhdəlikləri'), ('DELIVERY', 'Çatdırılma şərtləri')], max_length=20, verbose_name='Başlıq')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mətn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir?')),
            ],
            options={
                'verbose_name': 'Satış şərti',
                'verbose_name_plural': 'Satış şərtləri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mentioned_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
