# Generated by Django 4.2.7 on 2023-11-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_backlog_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mentioned_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
