# Generated by Django 4.2.7 on 2023-11-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pp',
            field=models.ImageField(blank=True, upload_to='UsersPPs/'),
        ),
    ]
