# Generated by Django 4.2.7 on 2023-11-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.AddField(
            model_name='user',
            name='mobil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
