# Generated by Django 4.2.7 on 2025-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('web', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.CharField(blank=True, max_length=70, null=True)),
                ('reference', models.CharField(choices=[('Seçilməyib', 'Seçilməyib'), ('Biz tapmışıq', 'Biz tapmışıq'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('WEB', 'WEB'), ('Eşitmə', 'Eşitmə')], max_length=15)),
                ('c_type', models.CharField(choices=[('Müştəri', 'Müştəri'), ('Partnyor', 'Partnyor')], max_length=10, verbose_name='customer type')),
                ('c_category', models.CharField(choices=[('Seçilməyib', 'Seçilməyib'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, verbose_name='customer category')),
                ('potency', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('pp', models.ImageField(blank=True, upload_to='CustomersPPs/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
