# Generated by Django 4.2.7 on 2023-11-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_potency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='potency',
            field=models.CharField(blank=True, choices=[('Pis', 'Pis'), ('Orta', 'Orta'), ('Yaxşı', 'Yaxşı')], max_length=6, null=True),
        ),
    ]
