# Generated by Django 4.2.7 on 2023-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_company_name_alter_customer_potency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
