# Generated by Django 4.2.7 on 2023-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reference',
            field=models.CharField(choices=[('Biz tapmışıq', 'Biz tapmışıq'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('WEB', 'WEB'), ('Eşitmə', 'Eşitmə')], max_length=15),
        ),
    ]
