# Generated by Django 4.2.7 on 2025-07-23 17:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Aktiv', 'Aktiv'), ('Uğurlu', 'Uğurlu'), ('Uğursuz', 'Uğursuz')], default='Aktiv', max_length=8, null=True)),
                ('status_change_reason', models.TextField(blank=True, null=True)),
                ('potency', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.offer_image_uploader)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_offers', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(default='001', max_length=3, verbose_name='number')),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pay_delv_cond', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('delv_time', models.CharField(max_length=30, verbose_name='delivery time')),
                ('is_active', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_revisions', to='sales.offer')),
                ('offer_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_approved_offers', to=settings.AUTH_USER_MODEL)),
                ('offer_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRevisionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('tax', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('delv', models.PositiveIntegerField(blank=True, null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_packages', to='sales.offerrevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRevisionPackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='sales.offerrevisionpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_services', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceUsedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_useds', to='products.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_used_products', to='sales.offerrevisionpackageservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.TextField()),
                ('plan_note', models.TextField(blank=True, null=True)),
                ('equipment_note', models.TextField(blank=True, null=True)),
                ('production_note', models.TextField(blank=True, null=True)),
                ('packaging_note', models.TextField(blank=True, null=True)),
                ('transportation_note', models.TextField(blank=True, null=True)),
                ('installation_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('prepayment', models.TextField(max_length=255)),
                ('nps', models.TextField(blank=True, null=True, verbose_name='next payment  schedule')),
                ('status_change_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Davamedir', 'Davamedir'), ('Tamamlandı', 'Tamamlandı')], default='Davamedir', max_length=11)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('question_corporation_profency', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('question_operativeness', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('question_personals_communication', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('question_delv_install_team', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('question_order_expectation', models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True)),
                ('handover', models.ImageField(blank=True, upload_to='OrderHandovers/', verbose_name='handover')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_orders', to='sales.contract')),
                ('order_accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_accountant', to=settings.AUTH_USER_MODEL)),
                ('order_installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_install', to=settings.AUTH_USER_MODEL)),
                ('order_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_production', to=settings.AUTH_USER_MODEL)),
                ('order_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_orders', to=settings.AUTH_USER_MODEL)),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saller_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_contracts', to='sales.offer'),
        ),
    ]
