# Generated by Django 4.2.7 on 2023-11-16 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_number', models.CharField(default='REV001', max_length=7, verbose_name='revision number')),
                ('note', models.TextField(blank=True, null=True)),
                ('prepayment', models.PositiveIntegerField()),
                ('lastpayment', models.PositiveIntegerField()),
                ('delv_fee', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Uğurlu', 'Uğurlu'), ('Uğursuz', 'Uğursuz')], max_length=8)),
                ('finish_reason', models.TextField(blank=True, null=True)),
                ('potency', models.FloatField(default=0.0)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_offer', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='sales.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('desc', models.TextField(max_length=255, verbose_name='description')),
                ('img', models.ImageField(blank=True, upload_to='OfferPackgeImgs/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_material', to='products.material')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orderservice', to='sales.orderservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, max_length=155, null=True)),
                ('plan_time', models.CharField(blank=True, max_length=20, null=True)),
                ('equipment', models.CharField(blank=True, max_length=155, null=True)),
                ('production', models.CharField(blank=True, max_length=155, null=True)),
                ('packaging', models.CharField(blank=True, max_length=155, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('installation', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('edv', models.FloatField(default=0.0)),
                ('prepayment', models.CharField(blank=True, max_length=100, null=True)),
                ('ncp', models.CharField(blank=True, max_length=100, null=True, verbose_name='next payment  schedule')),
                ('order_accountant', models.CharField(blank=True, max_length=30, null=True)),
                ('order_production', models.CharField(blank=True, max_length=30, null=True)),
                ('order_install', models.CharField(blank=True, max_length=30, null=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_order', to='customers.customer')),
                ('order_recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_order', to=settings.AUTH_USER_MODEL)),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saller_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferPackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('desc', models.TextField(max_length=255, verbose_name='description')),
                ('img', models.ImageField(blank=True, upload_to='OfferPackgeImgs/', verbose_name='image')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_package', to='sales.offerpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
