# Generated by Django 4.2.7 on 2025-07-23 11:38

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.offer_image_uploader),
        ),
    ]
