# Generated by Django 4.2.7 on 2023-11-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delv_fee',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='lastpayment',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='note',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rev_number',
        ),
        migrations.RemoveField(
            model_name='offerpackage',
            name='offer',
        ),
        migrations.AddField(
            model_name='offerpackageservice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='handover',
            field=models.ImageField(blank=True, upload_to='OrderHandovers/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Davamedir', 'Davamedir'), ('Ləğv', 'Ləğv'), ('Tamamlandı', 'Tamamlandı')], default='Davamedir', max_length=11),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderservicematerial',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderservicematerial',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='OfferRevison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(default='REV001', max_length=7, verbose_name='number')),
                ('note', models.TextField(blank=True, null=True)),
                ('prepayment', models.PositiveIntegerField()),
                ('lastpayment', models.PositiveIntegerField()),
                ('delv_fee', models.FloatField(default=0.0, verbose_name='delivery fee')),
                ('is_active', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_revision', to='sales.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offerpackage',
            name='revision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revision_package', to='sales.offerrevison'),
            preserve_default=False,
        ),
    ]
