# Generated by Django 4.2.7 on 2023-11-17 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_alter_customer_potency'),
        ('products', '0002_remove_material_price_remove_product_price'),
        ('sales', '0002_remove_offer_delv_fee_remove_offer_lastpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrevison',
            name='delv_time',
            field=models.CharField(default=2, max_length=30, verbose_name='delivery time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_orders', to='sales.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='finish_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_offers', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='potency',
            field=models.CharField(choices=[('Pis', 'Pis'), ('Orta', 'Orta'), ('Yaxşı', 'Yaxşı')], max_length=6),
        ),
        migrations.AlterField(
            model_name='offerpackage',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_packages', to='sales.offerrevison'),
        ),
        migrations.AlterField(
            model_name='offerpackageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_packages', to='sales.offerpackage'),
        ),
        migrations.AlterField(
            model_name='offerpackageservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='offerrevison',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_revisions', to='sales.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='saller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saller_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_producs', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderservicematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_materials', to='products.material'),
        ),
        migrations.AlterField(
            model_name='orderservicematerial',
            name='order_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orderservices', to='sales.orderservice'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_contract', to='sales.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
