# Generated by Django 4.2.7 on 2023-11-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_material_price_remove_product_price'),
        ('sales', '0004_alter_offer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceSystemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='offerpackageservice',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='edv',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='OrderServiceMaterial',
        ),
        migrations.AddField(
            model_name='orderservicesystemproduct',
            name='order_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orderservicesystems', to='sales.orderservice'),
        ),
        migrations.AddField(
            model_name='orderservicesystemproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_system_products', to='products.product'),
        ),
    ]
