# Generated by Django 4.2.7 on 2023-11-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_material_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_customer_phone'),
        ('sales', '0005_orderservicesystemproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_contract', to='sales.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_offers', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='offerpackageservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_orders', to='sales.contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='saller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saller_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_producs', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderservicesystemproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_system_products', to='products.product'),
        ),
    ]
