# Generated by Django 4.2.7 on 2023-11-23 15:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_contract_offer_alter_offer_costumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
