# Generated by Django 4.2.7 on 2023-11-23 15:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_offer_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
