# Generated by Django 4.2.7 on 2023-11-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_lastpayment_offerrevison_prepayment_precent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='costumer',
            new_name='customer',
        ),
    ]
