# Generated by Django 4.2.7 on 2023-11-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_material_product_unit'),
        ('sales', '0011_rename_costumer_offer_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferRevison',
            new_name='OfferRevision',
        ),
        migrations.RenameModel(
            old_name='OfferPackage',
            new_name='OfferRevisionPackage',
        ),
        migrations.RenameModel(
            old_name='OfferPackageService',
            new_name='OfferRevisionPackageService',
        ),
    ]
