# Generated by Django 4.2.7 on 2023-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_offerrevisionpackageservice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevision',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='number'),
        ),
    ]
