# Generated by Django 4.2.7 on 2023-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_offerrevision_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevision',
            name='number',
            field=models.CharField(default='001', max_length=3, verbose_name='number'),
        ),
    ]
