# Generated by Django 4.2.7 on 2023-11-29 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0015_alter_offerrevision_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrevision',
            name='offer_approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_approved_offers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrevision',
            name='offer_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_created_offers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
