# Generated by Django 4.2.7 on 2023-12-07 16:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_offerrevision_offer_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerrevision',
            name='delv_fee',
        ),
        migrations.RemoveField(
            model_name='offerrevision',
            name='prepayment_precent',
        ),
        migrations.RemoveField(
            model_name='offerrevisionpackageservice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='offerrevision',
            name='pay_delv_cond',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerrevisionpackage',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerrevisionpackage',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Faiz', 'Faiz'), ('Məbləğ', 'Orta')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='offerrevisionpackage',
            name='tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerrevision',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerrevisionpackageservice',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
