# Generated by Django 4.2.7 on 2023-12-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_rename_discount_amount_offerrevisionpackage_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevisionpackageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_services', to='sales.offerrevisionpackage'),
        ),
    ]
