# Generated by Django 4.2.7 on 2023-12-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_offerrevisionpackageservice_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevisionpackageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='sales.offerrevisionpackage'),
        ),
    ]
