# Generated by Django 4.2.7 on 2023-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_offerrevisionpackageservice_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevisionpackageservice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
