# Generated by Django 4.2.7 on 2023-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_offerrevisionpackageservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrevisionpackage',
            name='tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
