# Generated by Django 4.2.7 on 2023-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_offerrevisionpackage_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='finish_reason',
            new_name='status_change_reason',
        ),
        migrations.AlterField(
            model_name='offer',
            name='potency',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
    ]
