# Generated by Django 4.2.7 on 2023-12-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0024_orderserviceusedproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ncp',
            new_name='nps',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan_time',
        ),
        migrations.AddField(
            model_name='order',
            name='plan_note',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_accountant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_accountant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_install',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_install', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_production',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_production', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='project_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
