# Generated by Django 4.2.7 on 2023-12-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_remove_order_edv_remove_order_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='finish_reason',
            new_name='status_change_reason',
        ),
    ]
