# Generated by Django 4.2.7 on 2023-12-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_serviceusedproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceusedproduct',
            old_name='order_service',
            new_name='service',
        ),
    ]
