# Generated by Django 4.2.7 on 2023-12-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_rename_order_install_order_order_installer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='question_corporation_profency',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='question_delv_install_team',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='question_operativeness',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='question_order_expectation',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='question_personals_communication',
            field=models.CharField(blank=True, choices=[('PİS', 'PİS'), ('ORTA', 'ORTA'), ('YAXŞI', 'YAXŞI')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Davamedir', 'Davamedir'), ('Tamamlandı', 'Tamamlandı')], default='Davamedir', max_length=11),
        ),
    ]
