# Generated by Django 4.2.7 on 2024-01-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_contract_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrevisionpackage',
            name='delv',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
