# Generated by Django 4.2.7 on 2024-01-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_order_equipment_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='installation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nps',
            field=models.TextField(blank=True, null=True, verbose_name='next payment  schedule'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packaging_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='project_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='transportation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
