# Generated by Django 4.2.7 on 2023-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_orderservicesystemproduct_and_more'),
        ('products', '0002_remove_material_price_remove_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
